Here is the complete workflow file content you can use: yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install dependencies using npm
      - name: Install dependencies
        run: |
          npm install

      # Build the app (this will create the dist directory by default with Vite)
      - name: Build the app
        run: |
          npm run build

      # Deploy the app to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MUD_0EF70881E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (PR comments)
          action: "upload"
          app_location: "/" # The location of your source code (relative path, in your case it's the root folder)
          api_location: "api" # The location of your API code (empty if not using Azure Functions)
          output_location: "dist" # The output directory from Vite (typically 'dist')

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_MUD_0EF70881E }}
          action: "close"
